### ISSUE TITLE
[Critical Error] An unhandled exception occurred.

### ISSUE THREAD

**Issue by zhongjis** [fmmmlee/GW2-Addon-Manager#17]
**Describe the bug**
Critical Error pops up every time after ran program as administrator once. Fresh download does not work also.

**To Reproduce**
Run program as administrator

**Additional context**
![image](https://user-images.githubusercontent.com/23202735/75372464-737dc500-587d-11ea-9ef3-34e9b25f8a39.png)

**config.yaml**
this file does not exist for my fresh install (it only has a template file). But I have Manager.exe.config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="resources\plugins" />
      <dependentAssembly>
        <assemblyIdentity name="CommonServiceLocator" publicKeyToken="489b6accfaf20ef0" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.5.0" newVersion="2.0.5.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="YamlDotNet" publicKeyToken="ec19458f3c15af5e" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by fmmmlee** [comment]
The program uses the Github API to check versions of addons and dependencies, so if it's run a lot of times in a row the API hits a limit for your IP and returns a 403 error. The issue should go away automatically in an hour or so; I've only encountered it when I run the program many times during testing and it always goes away on its own when I wait a while (or if I go to another place, like my university, and then continue working there since it has a different IP address).

If you find this is the case, feel free to close the issue.

**Comment by zhongjis** [comment]
Sounds good. I'll test it out:) also if you don't mind I can make a pr for the README about this info. I think this might be worth mentioning alongside with [issue$14](https://github.com/fmmmlee/GW2-Addon-Manager/issues/14). Cuz I think I passed my API limit while trying to fix #14

**Comment by fmmmlee** [comment]
Sure, a PR is fine. You can do it for the README or to add a troubleshooting section in the wiki with that info.

**Comment by zhongjis** [comment]
sounds good. ill close this issue and start working on that.
