### ISSUE TITLE
Multiboxing Issue with Chromium

### ISSUE THREAD

**Issue by WolfSabian** [fmmmlee/GW2-Addon-Manager#213]
### Please attach a copy of config.yaml or config.ini to the issue.

I will attach the above if still necessary.

Since the May 23rd update I am no longer able to launch arcdps with more than one client unless I forced the use of coherent for the other clients with the -usecoherent argument.

I've confirmed this with some others I know who use arc and multiple simultaneous clients, and specifically add-on manager. This is only an issue using add-on manager  This is also an issue regardless of multiboxing client (gw2launcher or GW2LaunchBuddy).

I can upload whatever you think could help diagnose and resolve this issue

**Comment by Zyian** [comment]
Using ArcDPS with multiple clients should never have worked since Arc takes a lock on some of their own files. I'm not sure about the interaction between ArcDPS and CEF. But regardless this is also out of scope of the addon manager since it has no baring on how the actual game performs, it purely drops files in locations.

You can try to perform a clean install of all of your addons, and following the multiboxing setup for the launcher you use, there's a reinstall addon-loader function in the manager now that would recommend using.

You can also ask in the Elite Insights discord: https://discord.gg/RaZ5myp
Where ArcDPS is better supported since this project doesn't provide support for the individual addons.

**Comment by WolfSabian** [comment]
Can do. Unfortunately, I imagine the response will be similar, as the issue appears to only be an issue when add-on manager is used.

I'm still testing some things and can reply back here if and when I find more info that may be relevant.

**Comment by Zyian** [comment]
This comment should help you as well, looks like the patch changed CEF, and that is the root of your issue: https://github.com/Healix/Gw2Launcher/issues/316#issuecomment-1561612555

**Comment by Friendly0Fire** [comment]
Regardless, this is not an addon manager *or* addon loader issue. It's up to the launcher to handle this correctly.
