### ISSUE TITLE
Crashing on GW2 Radial download

### ISSUE THREAD

**Issue by d3fr0st** [fmmmlee/GW2-Addon-Manager#3]
As soon as I try to update with gw2 radial checked the executable hard crashes, disabling firewall/antivirus, running as admin nothing works. The bar says "Downloading GW2Radial V1.2.4" and crashes never gets to install.

**Comment by fmmmlee** [comment]
Can I have a copy of config.ini and a log file if it exists? Thanks

**Comment by fmmmlee** [comment]
Oh, and just to be sure - this occurred while the game was not running, right?

**Comment by d3fr0st** [comment]
Game ain't running, no log file I can get you a .dmp but it seems like straight memory addresses. Crash happens before the bar tries to fill up but with the gw2 radial version showing for download
[config.ini.txt](https://github.com/fmmmlee/GW2-Addon-Manager/files/3563057/config.ini.txt)

**Comment by d3fr0st** [comment]
> {
>   "application_version": "v0.4.2",
>   "bin_folder": "bin64",
>   "isupdate": true,
>   "arcDPS": "d3d9.dll",
>   "arcDPS_buildTemplates": "d3d9_arcdps_buildtemplates.dll",
>   "gw2Radial": "d3d9_chainload.dll",
>   "d912pxy": "d912pxy.dll",
>   "game_path": "C:\\Program Files\\Guild Wars 2",
>   "default_configuration": {
>     "arcdps": false,
>     "gw2radial": false,
>     "d912pxy": false,
>     "arcdps_bhud": false,
>     "arcdps_mechanics": false
>   },
>   "version": {
>     "arcdps": "6669ef8fcc2c817eb87b8516dcdbca76  x64/d3d9.dll\n",
>     "gw2radial": null,
>     "d912pxy": "v1.6",
>     "arcdps_bhud": "v0.2.4",
>     "arcdps_mechanics": "39af47dea0d955e181aea205c0ec6a7c\r\n"
>   },
>   "installed": {
>     "arcdps": "d3d9.dll",
>     "gw2radial": "d3d9.dll",
>     "d912pxy": "d912pxy.dll",
>     "arcdps_bhud": "arcdps_bhud.dll",
>     "arcdps_mechanics": "d3d9_arcdps_mechanics.dll"
>   },
>   "disabled": {
>     "arcdps": false,
>     "gw2radial": false,
>     "d912pxy": false,
>     "arcdps_bhud": false,
>     "arcdps_mechanics": false
>   }
> }

**Comment by fmmmlee** [comment]
Thanks, I just uploaded a release that should fix the hard crash to desktop issue; an error message should display now and a log file be created/added to in all crash cases.

**Comment by fmmmlee** [comment]
As far as your specific issue goes, I have no idea how gw2radial's entry in "installed" got to be d3d9.dll, but try manually editing it back to null (with no quotes around it), like so:

`{
"application_version": "v0.4.2",
"bin_folder": "bin64",
"isupdate": true,
"arcDPS": "d3d9.dll",
"arcDPS_buildTemplates": "d3d9_arcdps_buildtemplates.dll",
"gw2Radial": "d3d9_chainload.dll",
"d912pxy": "d912pxy.dll",
"game_path": "C:\Program Files\Guild Wars 2",
"default_configuration": {
"arcdps": false,
"gw2radial": false,
"d912pxy": false,
"arcdps_bhud": false,
"arcdps_mechanics": false
},
"version": {
"arcdps": "6669ef8fcc2c817eb87b8516dcdbca76 x64/d3d9.dll\n",
"gw2radial": null,
"d912pxy": "v1.6",
"arcdps_bhud": "v0.2.4",
"arcdps_mechanics": "39af47dea0d955e181aea205c0ec6a7c\r\n"
},
"installed": {
"arcdps": "d3d9.dll",
"gw2radial": null,
"d912pxy": "d912pxy.dll",
"arcdps_bhud": "arcdps_bhud.dll",
"arcdps_mechanics": "d3d9_arcdps_mechanics.dll"
},
"disabled": {
"arcdps": false,
"gw2radial": false,
"d912pxy": false,
"arcdps_bhud": false,
"arcdps_mechanics": false
}
}`

Then you can try downloading gw2radial again. I'm fairly certain it won't work (since clearly something is broken) but it'll help shed light on the issue at any rate.

**Comment by fmmmlee** [comment]
{
"application_version": "v0.4.2",
"bin_folder": "bin64",
"isupdate": true,
"arcDPS": "d3d9.dll",
"arcDPS_buildTemplates": "d3d9_arcdps_buildtemplates.dll",
"gw2Radial": "d3d9_chainload.dll",
"d912pxy": "d912pxy.dll",
"game_path": "C:\Program Files\Guild Wars 2",
"default_configuration": {
"arcdps": false,
"gw2radial": false,
"d912pxy": false,
"arcdps_bhud": false,
"arcdps_mechanics": false
},
"version": {
"arcdps": "6669ef8fcc2c817eb87b8516dcdbca76 x64/d3d9.dll\n",
"gw2radial": null,
"d912pxy": "v1.6",
"arcdps_bhud": "v0.2.4",
"arcdps_mechanics": "39af47dea0d955e181aea205c0ec6a7c\r\n"
},
"installed": {
"arcdps": "d3d9.dll",
"gw2radial": null,
"d912pxy": "d912pxy.dll",
"arcdps_bhud": "arcdps_bhud.dll",
"arcdps_mechanics": "d3d9_arcdps_mechanics.dll"
},
"disabled": {
"arcdps": false,
"gw2radial": false,
"d912pxy": false,
"arcdps_bhud": false,
"arcdps_mechanics": false
}
}

**Comment by d3fr0st** [comment]
Got it working. GW2Radial.zip was already in my temp folder and the program was getting denied from overwriting it

**Comment by fmmmlee** [comment]
Oh, thank you! Did you discover that just by poking around or did an error message point you in the right direction? Also, I thought that DownloadFileTaskAsync() overwrote by default....guess not, I'll have to put something in to check for existing temp files and delete.

**Comment by d3fr0st** [comment]
The crash message lead me to the issue

**Comment by fmmmlee** [comment]
good to know they can be useful, cheers!
